name: Build and Release Game

on:
  push:
    branches: [main]
  workflow_dispatch:   # allows manual triggering

permissions:
  contents: write       # required for creating releases and uploading assets

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Latest Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pygame

      - name: Build Windows Executable
        run: |
          pyinstaller --onefile gamefile.py

      - name: Prepare Release Files
        run: |
          mkdir release_assets
          copy dist\gamefile.exe release_assets\
          # Also include your existing Linux binary if it's in dist/
          if exist dist\gamefile (copy dist\gamefile release_assets\)
          if exist dist\gamefile-linux (copy dist\gamefile-linux release_assets\)

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Release"
          files: release_assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
